"""add identity_types and genders catalogs

Revision ID: b2948a4f42f0
Revises: 
Create Date: 2026-01-22 13:38:43.382714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2948a4f42f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'cost',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'attributes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_products_org_id'), 'products', ['org_id'], unique=False)
    op.add_column('users', sa.Column('identity_type_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('gender_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'identity_types', ['identity_type_id'], ['id'])
    op.create_foreign_key(None, 'users', 'genders', ['gender_id'], ['id'])
    op.drop_column('users', 'identity_type')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('identity_type', postgresql.ENUM('RUC', 'DNI', 'PASSPORT', 'FOREIGN_ID', name='identitytype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'gender_id')
    op.drop_column('users', 'identity_type_id')
    op.drop_index(op.f('ix_products_org_id'), table_name='products')
    op.alter_column('products', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
